COMMON_FLAGS="-O2 -march=native -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
MAKEOPTS="-j$(( $(nproc) * 3 / 4 )) -l$(( $(nproc) * 3 / 4 ))"
DISTDIR="/System/Portage/distfiles"
PKGDIR="/System/Portage/binpkgs"
VIDEO_CARDS="amdgpu"
L10N="pt-BR en-US"
ACCEPT_LICENSE="*"